tfwrap-terraform-install: Correct some spaces

diff --git a/tfwrap-terraform-install b/tfwrap-terraform-install
--- a/tfwrap-terraform-install
+++ b/tfwrap-terraform-install
@@ -101,7 +101,7 @@ curl -fLOsS "${url_prefix}/${checksum_sig_file}"
 
 if [ -z "$TFWRAP_TERRAFORM_SKIP_VERIFY" ]; then
 	command_exists gpgv ||
-		err "The command 'gpgv' is not found! Install GnuPG or \
+		err "The command 'gpgv' is not found!  Install GnuPG or \
 define TFWRAP_TERRAFORM_SKIP_VERIFY to skip verification!"
 
 	debug "Verifying checksum signature"
@@ -113,7 +113,7 @@ define TFWRAP_TERRAFORM_SKIP_VERIFY to skip verification!"
 define TFWRAP_TERRAFORM_SKIP_VERIFY to skip verification!"
 
 	debug "Verifying dist checksum"
-	grep -F -e "${dist_file}" "${checksum_file}" | shasum  -c - >/dev/null ||
+	grep -F -e "${dist_file}" "${checksum_file}" | shasum -c - >/dev/null ||
 		err "Checksum failed for: ${terraform_dist_dir}/${dist_file} with ${terraform_dist_dir}/${checksum_file}"
 else
 	debug "\$TFWRAP_TERRAFORM_SKIP_VERIFY is set, skipping dist verify"
@@ -121,7 +121,7 @@ fi
 
 if [ -z "$TFWRAP_TERRAFORM_SKIP_EXTRACT" ]; then
 	command_exists unzip ||
-		err "The command 'unzip' is not found! Please install Unzip \
+		err "The command 'unzip' is not found!  Please install Unzip \
 or define TFWRAP_TERRAFORM_SKIP_EXTRACT to skip extration of the downloaded distribution."
 
 	terraform_bin_dir="$TFWRAP_TERRAFORM_BASEDIR/$version"
